export const showTypes = {
  SHOW_SELECT_MOVIE: 'SHOW_SELECT_MOVIE',
  SHOW_MANIFEST_REQUEST: 'SHOW_MANIFEST_REQUEST',
  SHOW_MANIFEST_RECEIVED: 'SHOW_MANIFEST_RECEIVED',
  SHOW_VIDEO_DURATION: 'SHOW_VIDEO_DURATION',
  SHOW_VIDEO_POSITION: 'SHOW_VIDEO_POSITION',
  SHOW_VIDEO_STATE_TOGGLE: 'SHOW_VIDEO_STATE_TOGGLE',
  SHOW_VIDEO_FULLSCREEN_TOGGLE: 'SHOW_VIDEO_FULLSCREEN_TOGGLE',
  SHOW_VIDEO_FINISHED: 'SHOW_VIDEO_FINISHED'
}
